services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: gabdx
      POSTGRES_PASSWORD: 17
      POSTGRES_DB: processing-data
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    command: redis-server --requirepass 17!
    ports:
      - '6379:6379'

volumes:
  postgres_data:
